//facility model schema

var mongoose=require('mongoose'),
 Schema = mongoose.Schema;

var FacilitySchema = new Schema ({
    ANC : String, 
    ART : String, 
    BEOC : String, 
    BLOOD : String, 
    Beds : Number, 
    CAES_SEC : String, 
    CEOC : String, 
    C_IMCI : String, 
    Constituency : String, 
    Cots : Number, 
    County : String, 
    DescriptionOfLocation : String, 
    District : String, 
    Division: String, 
    EPI: String, 
    FP : String, 
    FacilityCode : Number, 
    FacilityName : String, 
    GROWM : String, 
    HBC : String, 
    HCT : String, 
    IPD : String, 
    InCharge : String, 
    Index : Number, 
    JobTitleofInCharge : String, 
    Location : String, 
    NearestTown : String, 
    OPD: String, 
    OUTREACH: String, 
    OfficalAddress : String, 
    OfficalAlternateNo : String, 
    OfficalEmail : String, 
    OfficalFAx : String, 
    OfficalLandline: String, 
    OfficalMobile: String, 
    Open24Hours : String, 
    OpenWeekends : String, 
    OperationalStatus: String, 
    Owner: String, 
    PMTCT : String, 
    PostCode : String, 
    Province : String, 
    RAD_XRAY : String, 
    RHTC_RHDC : String, 
    SubCounty : String, 
    SubLocation: String, 
    TB_DIAG : String, 
    TB_LABS : String, 
    TB_TREAT: String, 
    Tier : String, 
    Town : String, 
    Type : String, 
    YOUTH: String, 
    backed_up: Number, 
    created_at: { type: Date,required:true}, 
    updated_at : { type: Date,required:true}

}, { collection: 'Facilities'});


module.exports = mongoose.model('Facility', FacilitySchema);
